modules_dir = "artifacts/"

[[module]]
    name = "sqlite3"
    max_heap_size = "100  KiB"
    logger_enabled = true

    [module.wasi]
    preopened_files = ["./tmp"]
    mapped_dirs = { "./tmp" = "./tmp" }

[[module]]
    name = "account"
    logger_enabled = true
    max_heap_size = "100 KiB"
